name: Get VideoOFFAir

on:
  schedule:
    - cron: '0 * * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install streamlink
      run: |
        pip install --user --upgrade streamlink
    - name: Get VideoOFFAirSTR5.m3u8
      run: |
        touch ./VideoOFFAir.m3u8
        sudo cat >./VideoOFFAir.m3u8 <<EOL               
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(streamlink --url --default-stream  --stream-url --output /home/runner/work/youtube.m3u https://www.youtube.com/c/tomorrowland best)
        EOL
           
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
